### ISSUE TITLE
cmake遇错

### ISSUE THREAD

**Issue by briteming** [Hackerl/ShadowSocks_cpp#3]
hi。

root@racknerd-7b97d8 ShadowSocks_cpp]# mkdir build
[root@racknerd-7b97d8 ShadowSocks_cpp]# cd build
[root@racknerd-7b97d8 build]# ls
[root@racknerd-7b97d8 build]# cmake ..
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Checking for module 'jsoncpp'
--   Package 'jsoncpp', required by 'virtual:world', not found
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:556 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:778 (_pkg_check_modules_internal)
  CMakeLists.txt:10 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/root/ShadowSocks_cpp/build/CMakeFiles/CMakeOutput.log".
[root@racknerd-7b97d8 build]#

如何解决？

**Comment by Hackerl** [comment]
```
apt: sudo apt install cmake pkg-config libgoogle-glog-dev libssl-dev libevent-dev libjsoncpp-dev
pacman: sudo pacman -S cmake pkgconf google-glog openssl libevent jsoncpp
```
这项目是我写着玩的，已经不维护了，推荐使用专业的翻墙工具。
